name: Validate backward compatibility
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  node-diff:
    name: Check for breaking node changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run node diff
        uses: comfy-org/node-diff@main
